---
language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - /^travis/
    - /^v.*/

stages:
  - name: test
  - name: deploy gh-pages
    if: (branch = master OR branch =~ /^v.*/) AND type != pull_request

jobs:
  include:
    - stage: test
      install: skip
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: deploy gh-pages
      script: skip
      install: skip
      deploy:
        - provider: script
          script: mvn --settings .maven.xml site -DskipTests=true -B && git add dokka
          on:
            all_branches: true
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            all_branches: true
